#!/usr/bin/env python3
import os
import sys
import argparse
import json
import tomllib
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

SONA_PATH = Path("sona")
WORDS_META_PATH = SONA_PATH / "words" / "metadata"
DEFINITIONS_PATH = SONA_PATH / "words" / "source" / "definitions.toml"
FONT_PATH = Path("tools/Fairfax.ttf")
BUILD_PATH = Path("build")
DICT_OUTPUT_PATH = BUILD_PATH / "dictionary_data.c"
GLYPHS_OUTPUT_PATH = BUILD_PATH / "bitmap_glyphs.c"

TOKI_PONA_ALPHABET = "aeijklmnopstuw"

GLYPH_WIDTH = 12
GLYPH_HEIGHT = 12
BYTES_PER_IMAGE = GLYPH_WIDTH * GLYPH_HEIGHT // 8

if GLYPH_HEIGHT * GLYPH_WIDTH != BYTES_PER_IMAGE * 8:
    raise ValueError("Only bitmap sizes divisible by 8 are acceptable, try 12*12")

def generate_manifest(word_categories: set[str]) -> list[dict]:
    manifest = []
    
    definitions = {}
    if DEFINITIONS_PATH.exists():
        with open(DEFINITIONS_PATH, "rb") as f:
            definitions = tomllib.load(f)
    
    if not WORDS_META_PATH.exists():
        raise FileNotFoundError(f"Word metadata missing at {WORDS_META_PATH}")
    
    for meta_file in sorted(WORDS_META_PATH.glob("*.toml")):
        word_key = meta_file.stem
        
        with open(meta_file, "rb") as f:
            meta = tomllib.load(f)
            
        category = meta.get("usage_category")
        if category not in word_categories:
            continue
        
        definition = definitions.get(word_key, "")
            
        ucsur_hex = meta.get("representations").get("ucsur")
        if not ucsur_hex:
            continue
        codepoint = int(ucsur_hex.replace("U+", ""), 16)
        
        manifest.append({
            "word": word_key,
            "ucsur": codepoint,
            "definition": definition,
            "category": category
        })
        
    return manifest

def escape_c_byte(b):
    if b == 0:
        return r"\000"
    elif b == ord('"'):
        return r'\"'
    elif b == ord('\n'):
        return r'\n'
    elif 32 <= b <= 126:
        return chr(b)
    else:
        return f"\\{b:03o}"

def generate_dictionary(manifest: list[dict]):
    string_table_bytes = bytearray()
    word_entries = []
    letter_index = {char: -1 for char in TOKI_PONA_ALPHABET}
    
    for i, item in enumerate(manifest):
        word = item["word"]
        first_char = word[0].lower()
        definition = item["definition"]
        
        def_offset = len(string_table_bytes)
        string_table_bytes.extend(definition.encode("utf-8"))
        string_table_bytes.append(0)
        
        word_entries.append(f'    {{ "{word}", {i}, {def_offset} }}')
        
        if first_char in letter_index and letter_index[first_char] == -1:
            letter_index[first_char] = i
        
    formatted_string_table = "".join(escape_c_byte(b) for b in string_table_bytes)
    
    word_count = len(word_entries)
    entries_formatted = ",\n".join(word_entries)
    index_formatted = ", ".join(str(letter_index[char]) for char in TOKI_PONA_ALPHABET)
    
    c_content = f"""// Generated by tools/generate_dictionary.py
#include "dictionary_data.h"

const dictionary_db_t g_dictionary = {{
    .word_count = {word_count},
    .words = (const word_entry_t[{word_count}]) {{
{entries_formatted}
    }},
    .def_string_table = "{formatted_string_table}",
    .letter_index = {{
    {index_formatted}
    }}
}};
"""

    DICT_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(DICT_OUTPUT_PATH, "w") as f:
        f.write(c_content)
    
    print(f"Generated {DICT_OUTPUT_PATH} from {len(manifest)} word entries")

def generate_glyphs(manifest: list[dict]):
    font = ImageFont.truetype(FONT_PATH, GLYPH_HEIGHT)
    ucsur_chars = [chr(item["ucsur"]) for item in manifest]
    
    canvas = Image.new('1', (GLYPH_WIDTH, GLYPH_HEIGHT), color=(0))
    draw = ImageDraw.Draw(canvas)
    
    t = f"const unsigned char bitmap_glyphs[{len(ucsur_chars)}][{BYTES_PER_IMAGE}] = ""{\n"
    
    for code in ucsur_chars:
        draw.text((0, 0), code, font=font, fill=(1))
        data = canvas.get_flattened_data()
        draw.rectangle([0,0,GLYPH_WIDTH,GLYPH_HEIGHT],0)
        bitmap = [0]*BYTES_PER_IMAGE
        for byte in range(BYTES_PER_IMAGE):
            for bit in range(8):
                bitmap[byte]<<=1
                bitmap[byte]|=data[byte*8 + bit]
        
        t += "  {" + ",".join(map(hex,bitmap)) + "},\n"
    
    GLYPHS_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(GLYPHS_OUTPUT_PATH, "w") as f:
            f.write(t+"};")
    
    print(f"Generated {GLYPHS_OUTPUT_PATH} from {len(manifest)} word entries")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dictionary", action='store_true',)
    parser.add_argument("--glyphs", action='store_true',)
    parser.add_argument("--categories", nargs="+", required=True)
    args = parser.parse_args()
    
    manifest = generate_manifest(set(args.categories))
    
    if args.dictionary:
        generate_dictionary(manifest)
    if args.glyphs:
        generate_glyphs(manifest)
    if not args.dictionary and not args.glyphs:
        print("No asset build target specified. Use '--dictionary' or '--glyphs'")

if __name__ == "__main__":
    main()